name: rss_core
description: RSS core module.
version: 0.0.1+20211023
homepage: https://github.com/i10416/rss-modules/core

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flechette:
    git:
      url: https://github.com/i10416/dart-modules.git
      path: flechette
  http: ^0.13.3
  meta: ^1.7.0
  metadata_fetch: ^0.4.1
  xml: ^5.2.0


dev_dependencies:
  lint: ^1.6.0
  test: ^1.17.11
