name: rss_view
description: rss view module.
version: 0.0.1+20220129
homepage: https://github.com/i10416/rss-modules/view
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  rss_core:
    git:
      url: https://github.com/i10416/rss-modules.git
      path: core
  flechette: ^0.0.1
  cached_network_image: ^3.0.0
  webview_flutter: ^3.0.0





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0