name: rss_view
description: rss view module.
version: 0.0.1
homepage: https://github.com/ItoYo16u/rss-modules/view
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  rss_core:
    git:
      url: git@github.com:ItoYo16u/rss-modules.git
      path: core
  flechette:
    git:
      url: git@github.com:ItoYo16u/dart-modules.git
      path: flechette
  cached_network_image: ^3.0.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0